# Generated by Django 2.1.15 on 2021-04-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=100)),
                ('top_color', models.CharField(max_length=100)),
                ('bottom', models.CharField(max_length=100)),
                ('bottom_color', models.CharField(max_length=100)),
                ('cape', models.BooleanField()),
                ('cape_color', models.CharField(max_length=100, null=True)),
                ('mask', models.BooleanField()),
                ('mask_color', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('aliases', models.CharField(max_length=200)),
                ('abilities', models.ManyToManyField(to='hero.Ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('motive', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='affiliations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hero.Team'),
        ),
        migrations.AddField(
            model_name='hero',
            name='costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearer', to='hero.Costume'),
        ),
        migrations.AddField(
            model_name='hero',
            name='weapons',
            field=models.ManyToManyField(to='hero.Weapon'),
        ),
    ]
