# Generated by Django 2.1.15 on 2021-04-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='cape_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='mask_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
